# Generated by Django 5.0.4 on 2024-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coscode',
            fields=[
                ('coscode', models.CharField(db_column='COSCODE', max_length=4, primary_key=True, serialize=False)),
                ('longname', models.CharField(db_column='LONGNAME', max_length=60, unique=True)),
                ('coshead', models.CharField(db_column='COSHEAD', max_length=45)),
            ],
            options={
                'db_table': 'coscode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distcode',
            fields=[
                ('distcode', models.CharField(blank=True, db_column='DISTCODE', max_length=4, primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, db_column='DISTRICT', max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofentry', models.DateTimeField(blank=True, db_column='DateOfEntry', null=True)),
                ('enteredby', models.CharField(blank=True, db_column='EnteredBy', max_length=45, null=True)),
            ],
            options={
                'db_table': 'distcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logid', models.AutoField(db_column='logId', primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('message', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minemast',
            fields=[
                ('mineid', models.AutoField(db_column='MineId', primary_key=True, serialize=False)),
                ('minecode', models.IntegerField(db_column='MINECODE')),
                ('mine', models.CharField(db_column='MINE', max_length=100)),
                ('minetype', models.CharField(blank=True, db_column='Minetype', max_length=45, null=True)),
                ('mnlcode', models.CharField(blank=True, db_column='Mnlcode', max_length=4, null=True)),
                ('mineral', models.CharField(db_column='MINERAL', max_length=45)),
                ('mineraltype', models.CharField(db_column='MineralType', max_length=10)),
                ('lin', models.CharField(blank=True, db_column='LIN', max_length=20, null=True)),
                ('state', models.CharField(db_column='STATE', max_length=40)),
                ('district', models.CharField(db_column='DISTRICT', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=150, null=True)),
                ('post', models.CharField(db_column='POST', max_length=50)),
                ('pincode', models.CharField(db_column='PINCODE', max_length=8)),
                ('zone', models.CharField(db_column='ZONE', max_length=30)),
                ('region', models.CharField(db_column='REGION', max_length=40)),
                ('subregion', models.CharField(blank=True, db_column='SUBREGION', max_length=40, null=True)),
                ('owncode', models.CharField(blank=True, db_column='Owncode', max_length=6, null=True)),
                ('ownsort', models.CharField(blank=True, db_column='OWNSORT', max_length=15, null=True)),
                ('owner', models.CharField(max_length=80)),
                ('opendate', models.CharField(blank=True, db_column='OPENDATE', max_length=20, null=True)),
                ('dateofentry', models.CharField(blank=True, db_column='DateOfEntry', max_length=20, null=True)),
                ('enteredby', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='EnteredBy', max_length=20, null=True)),
                ('entrysource', models.CharField(blank=True, db_column='EntrySource', max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=100, null=True)),
                ('verified', models.CharField(blank=True, db_column='Verified', max_length=1, null=True)),
                ('verifiedby', models.CharField(blank=True, db_column='VerifiedBy', max_length=45, null=True)),
                ('verify_date', models.CharField(blank=True, db_column='Verify_Date', max_length=20, null=True)),
            ],
            options={
                'db_table': 'minemast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mnlcode',
            fields=[
                ('mnlcode', models.CharField(blank=True, db_column='MNLCODE', max_length=4, primary_key=True, serialize=False)),
                ('mnlname', models.CharField(blank=True, db_column='MNLNAME', max_length=50, null=True)),
                ('mnltype', models.CharField(blank=True, db_column='MNLTYPE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'mnlcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ownmast',
            fields=[
                ('owncode', models.CharField(blank=True, db_column='OWNCODE', max_length=10, primary_key=True, serialize=False)),
                ('ownname', models.CharField(blank=True, db_column='OWNNAME', max_length=75, null=True)),
                ('own_short', models.CharField(blank=True, db_column='OWN_SHORT', max_length=10, null=True)),
                ('desig', models.CharField(blank=True, db_column='DESIG', max_length=45, null=True)),
                ('mnltype', models.CharField(blank=True, db_column='MNLTYPE', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=150, null=True)),
                ('po', models.CharField(blank=True, db_column='PO', max_length=70, null=True)),
                ('district', models.CharField(blank=True, db_column='DISTRICT', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=150, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='PINCODE', null=True)),
                ('ho_tel', models.CharField(blank=True, db_column='HO_Tel', max_length=150, null=True)),
                ('owner_tel', models.CharField(blank=True, db_column='Owner_Tel', max_length=150, null=True)),
                ('sector', models.TextField(blank=True, db_column='SECTOR', null=True)),
                ('remarks', models.TextField(blank=True, db_column='REMARKS', null=True)),
                ('entered_by', models.CharField(blank=True, db_column='ENTERED_BY', max_length=45, null=True)),
                ('entry_date', models.DateTimeField(blank=True, db_column='ENTRY_DATE', null=True)),
            ],
            options={
                'db_table': 'ownmast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode', models.IntegerField(blank=True, db_column='Pincode', primary_key=True, serialize=False)),
                ('post', models.CharField(db_column='Post', max_length=45)),
                ('officetype', models.CharField(blank=True, db_column='OfficeType', max_length=5, null=True)),
                ('district', models.CharField(db_column='District', max_length=55)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('circlename', models.CharField(blank=True, db_column='CircleName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pincode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rgncode',
            fields=[
                ('code', models.CharField(db_column='CODE', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('codetype', models.CharField(max_length=3)),
                ('active', models.CharField(db_column='ACTIVE', max_length=1)),
                ('subregion', models.CharField(db_column='SUBREGION', max_length=50)),
                ('region', models.CharField(db_column='REGION', max_length=50)),
                ('zone', models.CharField(db_column='ZONE', max_length=50)),
                ('add1', models.CharField(db_column='ADD1', max_length=80)),
                ('add2', models.CharField(db_column='ADD2', max_length=80)),
                ('remarks', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rgncode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rgncode2',
            fields=[
                ('rgncode', models.CharField(db_column='RGNCODE', max_length=3, primary_key=True, serialize=False)),
                ('rgnname', models.CharField(db_column='RGNNAME', max_length=45)),
                ('active', models.CharField(db_column='ACTIVE', max_length=1)),
                ('add1', models.CharField(db_column='ADD1', max_length=150)),
                ('add2', models.CharField(db_column='ADD2', max_length=150)),
                ('zonecode', models.CharField(db_column='ZONECODE', max_length=3)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=45)),
            ],
            options={
                'db_table': 'rgncode2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srgncode',
            fields=[
                ('srgncode', models.CharField(db_column='SRGNCODE', max_length=3, primary_key=True, serialize=False)),
                ('srgnname', models.CharField(db_column='SRGNNAME', max_length=40)),
                ('active', models.CharField(db_column='ACTIVE', max_length=1)),
                ('rgncode', models.CharField(db_column='RGNCODE', max_length=3)),
                ('zonecode', models.CharField(db_column='ZONECODE', max_length=3)),
                ('remarks', models.TextField(db_column='REMARKS')),
            ],
            options={
                'db_table': 'srgncode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State2',
            fields=[
                ('statecode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'state2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('statecode', models.TextField(blank=True, db_column='Statecode', primary_key=True, serialize=False)),
                ('statename', models.TextField(blank=True, db_column='StateName', null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestDtl',
            fields=[
                ('idtest_dtl', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=2)),
                ('dob', models.DateTimeField()),
                ('state', models.TextField()),
                ('coscode', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'test_dtl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('desig', models.CharField(max_length=45)),
                ('workassigned', models.CharField(max_length=45)),
                ('workcode', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=5)),
                ('entered_by', models.CharField(max_length=45)),
                ('entry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonecode',
            fields=[
                ('zonecode', models.CharField(db_column='ZONECODE', max_length=3, primary_key=True, serialize=False)),
                ('zonename', models.CharField(db_column='ZONENAME', max_length=45)),
                ('add1', models.CharField(db_column='ADD1', max_length=100)),
                ('add2', models.CharField(db_column='ADD2', max_length=100)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=50)),
            ],
            options={
                'db_table': 'zonecode',
                'managed': False,
            },
        ),
    ]
