# Generated by Django 5.0.4 on 2024-07-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aentry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distcode',
        ),
    ]
