# Generated by Django 5.0.4 on 2024-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aentry', '0002_delete_distcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distcode',
            fields=[
                ('distcode', models.CharField(blank=True, db_column='DISTCODE', max_length=4, primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, db_column='DISTRICT', max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofentry', models.DateTimeField(blank=True, db_column='DateOfEntry', null=True)),
                ('enteredby', models.CharField(blank=True, db_column='EnteredBy', max_length=45, null=True)),
            ],
            options={
                'db_table': 'distcode',
                'managed': False,
            },
        ),
    ]
