# Generated by Django 5.0.4 on 2024-07-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aentry', '0003_distcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coscode',
        ),
        migrations.DeleteModel(
            name='Distcode',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='Minemast',
        ),
        migrations.DeleteModel(
            name='Mnlcode',
        ),
        migrations.DeleteModel(
            name='Ownmast',
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.DeleteModel(
            name='Rgncode',
        ),
        migrations.DeleteModel(
            name='Rgncode2',
        ),
        migrations.DeleteModel(
            name='Srgncode',
        ),
        migrations.DeleteModel(
            name='State2',
        ),
        migrations.DeleteModel(
            name='States',
        ),
        migrations.DeleteModel(
            name='TestDtl',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Zonecode',
        ),
    ]
